fragment TeamListCard on teams {
  id
  name
  description
  creator {
    email
    displayName
  }
  user_teams {
    user {
      email
      profile {
        avatar
      }
      displayName
    }
  }
}
