mutation GameJoin($gameId: uuid!) {
  insert_user_game_one(object: { gameId: $gameId }) {
    id
    game {
      ...GameJoinConnected
    }
  }
}

fragment GameJoinConnected on games {
  id
  joinedByUser
  user_games {
    id
    userId
    gameId
  }
}
