fragment GameListCard on games {
  id
  timestamp
  joinedByUser
  status
  creator {
    email
    displayName
  }
  user_games {
    id
    userId
    user {
      email
      profile {
        avatar
      }
      displayName
    }
  }
  ...GameJoinConnected
  # ...GameJoinModal
  ...GameLeaveConnected
}
