fragment GameListCard on games {
  id
  timestamp
  joinedByUser
  creator {
    email
    displayName
  }
  user_games {
    user {
      email
      profile {
        avatar
      }
      displayName
    }
  }
}
